env:
  browser: true
  node: true
  es2021: true
#extends:
#  - airbnb
#  - airbnb/hooks
#  - airbnb/base
#  - plugin:react/recommended
#  - react-app
#  - react-app/jest
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
#plugins:
#  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-tabs: 0
#  react/jsx-indent:
#    - error
#    - tab
  react/jsx-indent-props: 0
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - state
  max-len:
    - error
    - code: 120

